# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **
      !.git/**/*
      !.gitignore
      !terraform/**/*
      !LICENSE
      !README.md
      !azure-pipelines.yml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  
- task: CmdLine@2
  inputs:
    script: |
      echo 'Source directory $(Build.SourcesDirectory)'
      
      echo 'artifact $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1